name: Update the ranking

on:
  pull_request:
    types: [labeled]

permissions:
  id-token: write
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-ranking:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'update-ranking' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Verify GeckoDriver installation
        run: geckodriver --version

      - name: Check system resources
        run: free -h && df -h

      - name: Run the tournament scraper
        run: pipenv run python -m fwango_scraper

      - name: Run the ranking update script
        run: pipenv run python -m ranking_calculator

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated ranking"
          git push
